<div class='container general-info terms-of-use'>
	<h1 class='general-info-title'>
		Terms of Use
	</h1>
	© Copyright 2018, Marriott Vacation Club International. All rights reserved.
	<br><br>
	The content and information ("MVCI Information") displayed on this Marriott Vacation Club International website ("Site") is the property of Marriott Vacation Club International, ("MVCI") and/or other parties. The downloading, reproduction, or retransmission of MVCI Information, other than for non-commercial individual use, is strictly prohibited. Please feel free to browse the Site at any time; however, by browsing this Site, you are subject to the terms and conditions ("Terms and Conditions") of this Site. By accessing this Site, you accept, without limitation or qualification, the following Terms and Conditions. If you do NOT accept the Terms and Conditions, then please discontinue your use of this Site.
	<br><br>
	<h2 class='general-info-header'>
		TERMS AND CONDITIONS
	</h2>
	<h3 class="general-info-cursive">
		Use of Site
	</h3>
	MVCI reserves the right, in its sole discretion, to amend the Terms and Conditions, and to modify, add or discontinue any aspect, content, or feature of the Site. Such amendments, modifications, additions, deletions shall become effective upon notice thereof, which may be provided to you by posting on the Site, via e-mail or any other means. Continued use of the Site by you shall constitute your binding acceptance of any such amendments, modifications, additions or deletions. The Site is owned and operated by MVCI and its affiliated companies and contains material that is derived in whole or in part from material supplied and owned by MVCI and other sources. Such material is protected by copyright, trademark, and other applicable laws. You may not modify, copy, reproduce, republish, upload, post, transmit, publicly display, prepare derivative works based on, or distribute in any way any material from the Site, including but not limited to text, audio, video, code and software. MVCI neither warrants nor represents that your use of materials displayed on the Site will not infringe rights of third parties not owned by or affiliated with MVCI. MVCI's Internet sites may contain or reference trademarks, patents, copyrighted materials, trade secrets, technologies, products, processes or other proprietary rights of MVCI and/or other parties. No license to or right in any such trademarks, patents, copyrighted materials, trade secrets, technologies, products, processes and other proprietary rights of MVCI and/or other parties is granted to or conferred upon you.
	<br><br>
	Marriott Vacation Club International and the programs and products provided under the Marriott Vacation Club brand is not owned, developed, or sold by Marriott International, Inc.  Marriott Vacation Club International uses the Marriott marks under license from Marriott International, Inc. and its affiliates.
	<br><br>
	You agree that you will make only legitimate reservations in good faith for use by you and your invited guests only, and not for other purposes, including without limitation, reselling, impermissibly assigning or posting on third party websites, or making speculative, false or fraudulent reservations, or any reservation in anticipation of demand.
	<h3 class="general-info-cursive">
		Limitation of Liability
	</h3>
	YOUR USE OF, AND BROWSING IN, THE SITE IS AT YOUR OWN RISK. YOU ASSUME FULL RESPONSIBILITY FOR IMPLEMENTING SUFFICIENT PROCEDURES AND CHECKS TO SATISFY YOUR REQUIREMENTS FOR THE ACCURACY AND SUITABILITY OF THE SITE, INCLUDING THE INFORMATION, AND FOR MAINTAINING ANY MEANS THAT YOU MAY REQUIRE FOR THE RECONSTRUCTION OF LOST DATA OR SUBSEQUENT MANIPULATIONS OR ANALYSES OF THE INFORMATION PROVIDED HEREUNDER. YOU ACKNOWLEDGE THAT YOUR USE OF THE SITE AND ANY INFORMATION SENT OR RECEIVED IN CONNECTION THEREWITH, MAY NOT BE SECURE AND MAY BE INTERCEPTED BY UNAUTHORIZED PARTIES. YOU ASSUME RESPONSIBILITY FOR THE ENTIRE COST OF ALL NECESSARY MAINTENANCE, REPAIR OR CORRECTION TO YOUR COMPUTER SYSTEM OR OTHER PROPERTY. IN NO EVENT SHALL MVCI, ITS PARENT OR SUBSIDIARY COMPANIES OR ITS AFFILIATES OR SUPPLIERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR OTHER DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THE SITE OR WITH THE DELAY OR INABILITY TO USE THE SITE, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS AND SERVICES ADVERTISED IN OR OBTAINED THROUGH THE SITE, MVCI'S REMOVAL OR DELETION OF ANY MATERIALS OR RECORDS SUBMITTED OR POSTED ON ITS SITE, OR OTHERWISE ARISING OUT OF THE USE OF THE SITE, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF MVCI OR ANY OF ITS SUBSIDIARY COMPANIES, AFFILIATES OR SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. THIS WAIVER APPLIES, WITHOUT LIMITATION, TO ANY DAMAGES OR INJURY ARISING FROM ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, FILE CORRUPTION, COMMUNICATION-LINE FAILURE, NETWORK OR SYSTEM OUTAGE, OR THEFT, DESTRUCTION, UNAUTHORIZED ACCESS TO, ALTERATION OF, OR USE OF ANY RECORD. YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT MVCI, ITS PARENT OR SUBSIDIARY COMPANIES, AFFILIATES OR SUPPLIERS SHALL NOT BE LIABLE FOR ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF ANY USER OF THE SITE. You agree that you will not use any device, software or other instrumentality to interfere or attempt to interfere with the proper working of the Site, and that you will not take any action that imposes an unreasonable or disproportionately large load on our infrastructure. In addition, you agree that you will not use any robot, spider, other automatic device, or manual process to monitor or copy our Web pages or the content contained herein, without the prior express consent from an authorized MVCI representative (such consent is deemed given for standard search engine technology employed by Internet search websites to direct Internet users to the Site).
	<br><br>
	The Site may provide you with the ability to use usernames, passwords, or other codes or devices to gain access to restricted portions of the Site ("access codes"). The content contained in such restricted areas is confidential to MVCI, and is provided to you for your personal use only. We reserve the right to prohibit the use of such access codes on your behalf by third parties where we determine that such use interferes with the Site's operation or results in commercial benefits for other entities to our detriment. You have a unique password so that access to information can be restricted to only those individuals to whom you provided the password. It is your responsibility to protect the confidentiality of the password. MVCI assumes no liability for any access to information or transactions that are executed with the password provided to you. We strongly recommend that you change the password on a periodic basis if you suspect that knowledge of the password is no longer limited to those that you have authorized.
	<h3 class="general-info-cursive">
		Submissions
	</h3>
	Any communication or material you do transmit to the Site by electronic mail or otherwise will be treated as non-confidential and non-proprietary. Anything you transmit or post shall be deemed the property of and may be used by MVCI, or its affiliates, for any purpose, including, but not limited to, reproduction, disclosure, transmission, publication, broadcast and posting. Furthermore, MVCI is free to use and shall be deemed to own, any ideas, concepts, know-how, or techniques contained in any communication you send to the Site for any purpose whatsoever, including, but not limited to, developing, producing, manufacturing, and marketing products and services using such information. Disclosure, postings, submission, or offer of any submissions to the Site shall constitute an assignment to MVCI of all worldwide rights, titles, and interests in all copyrights and other intellectual property rights in such submission. MVCI may edit, copy, publish, distribute, translate, and otherwise use in any medium any submission that you forward to MVCI or post on the Site and will own exclusively all such rights, titles, and interest and shall not be limited in any way in its use, commercial or otherwise, of the submission or posting. MVCI is and shall be under no obligation to: (1) maintain any of your or any user's submissions or postings in confidence; (2) to pay to you or any user any compensation for any submissions; or (3) to respond to any of your or any other user's submissions or postings.
    <h3 class="general-info-cursive">Copyright Protection</h3>
    If you believe in good faith that materials hosted on the Site infringe your copyright you may send written notice to the designated copyright agent for Marriott Vacations Worldwide Corporation on behalf of MVCI that includes the following information.  Please note that your complaint will not be processed if it is not properly filled out or is incomplete. Any misrepresentations in your notice regarding whether content or activity is infringing may expose you to liability for damages. <br /><br />
    <ul style="list-style: none;">
    	<li>(i) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.<br /><br /></li>
        <li>(ii) Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site.<br /><br /></li>
        <li>(iii) Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the MVCI to locate the material.<br /><br /></li>
        <li>(iv) Information reasonably sufficient to permit MVCI to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted.<br /><br /></li>
        <li>(v) A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.<br /><br /></li>
        <li>(vi) A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
	</ul><br />
    You may send your completed notice to us at Marriott Vacations Worldwide Corporation, 6649 Westwood Blvd., Orlando, FL 32821, attn: Law Dept. IP Counsel, or by email to <a class='general-info-link' href="mailto:copyright@mvwc.com">copyright@mvwc.com</a>. 

	<h3 class="general-info-cursive">
		Message Boards
	</h3>
	The Site may provide you and other users an opportunity to submit, post, display, transmit and/or exchange information, ideas, opinions, photographs, images, notes, video, creative works or other information, messages, transmissions or material to us, the Site or others ("Post" or "Postings"). Postings do not reflect the views of MVCI; and MVCI does not have any obligation to monitor, edit, or review any Postings on the Site. MVCI assumes NO responsibility or liability arising from the content of any such Postings nor for any error, defamation, libel, slander, omission, falsehood, obscenity, pornography, profanity, danger, or inaccuracy contained in any information within such Postings on the Site. You are strictly prohibited from posting or transmitting any unlawful, threatening, libelous, defamatory, obscene, scandalous, inflammatory, pornographic, or profane material that could constitute or encourage conduct that would be considered a criminal offense, give rise to civil liability, or otherwise violate any law. Marriot will fully cooperate with any law enforcement authorities or court order requesting or directing MVCI to disclose the identity of anyone posting any such information or materials.
	<br><br>
	Registration as a User of the Message Boards implies that you accept that you will not post any material likely to cause offense, that is protected by copyright, trademark or other proprietary right - without the express permission of the owner of such copyright - or that contains personal phone numbers or addresses. That you will not use the Message Boards to post or transmit advertisements or commercial solicitations of any kind. That MVCI or its agent has the right to edit, censor, delete or otherwise modify any posting. This Site does not verify or guarantee the accuracy of the material posted to the Message Boards or bear any responsibility for any loss, damage, or other liabilities caused by any posting.
	<br><br>
	MVCI may, in its sole discretion, terminate your Message Board password, account (or any part thereof) or your access to the Site, or remove and discard any communication transmitted by you, or information stored, sent, or received via the Site without prior notice and for any reason, including, but not limited to: (i) concurrent access of the Site with identical user identification numbers, (ii) permitting another person or entity to use your user identification number to access the Site, (iii) any other access or use of the Site except as expressly provided, (iv) any violation of the terms and conditions of these Terms and Conditions or the rules and regulations relating to the use of, the software and/or data files contained in, or accessed through, the Site, or (v) tampering with or alteration of any of the software and/or data files contained in, or accessed through, the Site. You may terminate your Message Board membership hereunder upon thirty (30) days written notice by you to MVCI of your intent to terminate. Termination, suspension, or cancellation of your access rights shall not affect any right or relief to which MVCI may be entitled, at law or in equity. Upon termination of your Message Board membership, all rights granted to you will automatically terminate and immediately revert to MVCI and its licensors.
	<h3 class="general-info-cursive">
		Disclaimer of Warranties
	</h3>
	While MVCI uses reasonable efforts to include up to date information in the Site, MVCI makes no warranties or representations as to its accuracy, timeliness, reliability, completeness or otherwise. The content, materials, and products or services available in or accessible through the Site are AS IS and, to the fullest extent permissible pursuant to applicable law, MVCI DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, AND WARRANTIES IMPLIED FROM A COURSE OF PERFORMANCE OR COURSE OF DEALING. MVCI DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN SUCH MATERIALS AND PRODUCTS, OR IN THE SITE, WILL BE UNINTERRUPTED OR ERROR-FREE, WILL BE AVAILABLE FOR USE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE, INCLUDING THE STORAGE SERVICES AND THEIR CONTENTS, OR THE SERVER THAT MAKES THEM AVAILABLE, ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. Some jurisdictions do not allow the exclusion of implied warranties, so the above exclusion may not apply to you.
	<h3 class="general-info-cursive">
		Technical Inaccuracies and Typographical Errors
	</h3>
	MVCI Information may contain technical inaccuracies and typographical errors, including but not limited to, inaccuracies relating to pricing or availability. MVCI shall not assume responsibility or liability for any such inaccuracies, errors or omissions, and shall have no obligation to honor information affected by such inaccuracies. MVCI reserves the right to make changes, corrections and/or improvements to MVCI Information, and to the products and programs described in such information, at any time without notice.
	<h3 class="general-info-cursive">
		Availability of Products and Services
	</h3>
	MVCI Internet sites contain information on MVCI's worldwide products and services, not all of which are available in every location. A reference to a MVCI product or service on a MVCI Internet site does not imply that such product or service is or will be available in your location.
	<h3 class="general-info-cursive">
		Indemnification
	</h3>
	You agree to indemnify, defend and hold MVCI and its subsidiaries, affiliates, and their respective officers, directors, owners, employees, agents, information providers and licensors (collectively the "Indemnified Parties") harmless from and against any and all claims, liability, losses, actions, suits, costs and expenses (including attorneys' fees) arising out of or incurred by any breach by you of these Terms and Conditions. MVCI reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with MVCI's defense of such claim.
	<h3 class="general-info-cursive">
		Non-MVCI Sites
	</h3>
	If you choose to leave the Site via links to other non-MVCI sites, including those of advertisers, MVCI is not responsible for the privacy policies of those sites or the cookies those sites use. In addition, because MVCI has no control over such sites and resources, you acknowledge and agree that MVCI is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products, or other materials on or available from such sites or resources.
	<h3 class="general-info-cursive">
		Governing Law
	</h3>
	This is a United States Web site and is subject to United States law. MVCI will disclose any information regarding the use of this Site including personal information pertaining to you without your permission when required by law, or in good faith belief that such action is necessary to investigate or protect against harmful activities to MVCI guests, visitors, associates, or property (including this site), or to others.
	<br><br>
	If you would like to view the privacy practices that govern this site please see our privacy statement posted on this site at <a id='privacy-link'>http://www.marriottvacationclub.com/general-information/privacy-policy.shtml</a>. If you have any questions about these Terms of Use or privacy concerns, please write us at 6649 Westwood Boulevard, Suite 500, Orlando, FL 32821 or send an e-mail to <a class='general-info-link' href='mailto:privacy@vacationclub.com'>privacy@vacationclub.com</a>.
</div>
<?php echo horizontalBreak(); ?>